name: Auto Blog Post

on:
  schedule:
    # 매일 2시간 간격으로 실행
    - cron: '0 */2 * * *'   # 매 2시간마다 실행
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run blog post script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        python generate_post.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@users.noreply.github.com'  # 이 이메일 형식을 사용하면 개인 정보를 보호할 수 있습니다.

    - name: Commit and Push changes
      run: |
        git add .
        git commit -m "Auto Blog" || echo "No changes to commit"  # 커밋할 변화가 없는 경우 에러 방지
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/LunaStev/lunastev.github.io
