name: Auto Blog Post

on:
  schedule:
    - cron: '0 */2 * * *'  # 매 2시간 간격으로 실행
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clean up old logs and caches
        run: |
          echo "Cleaning up old logs and caches..."
          find /home/runner/runners/ -name "*.log" -type f -delete || true
          rm -rf ~/.cache/pip/* || true
          rm -rf ~/.cache/* || true
          rm -rf /tmp/* || true
          echo "Disk usage after cleanup:"
          df -h  # 디스크 사용량 확인

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            **/venv/**  # 가상환경 캐시 (사용하는 경우)
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

      - name: Run blog post script
        run: |
          python generate_post.py

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commit and Push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add .
          git commit -m "Auto Blog-19" || echo "No changes to commit"
          git push https://${{ secrets.GH_TOKEN }}@github.com/LunaStev/lunastev.github.io.git
